# CS5600 Programming Assignment 1
# Sreesatya  Nandivada
# Date Goes Here
#####################################################################
#
#

#####################################################################



CC = gcc
CFLAGS = -Wall -Werror

TARGET = shell
SRC = shell.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
